### ISSUE TITLE
Slightly problematic new project setup

### ISSUE THREAD

**Issue by andytan0727** [Rexpert/TNG_Statement_in_CSV#11]
I have encountered several errors below when I'm trying to setup virtual env and install dependencies:

1. opencv issue

Version 4.9.0 not found

![image](https://github.com/user-attachments/assets/e1457198-d54b-4170-a32f-6d089d897d9b)

2. Numpy issue

```
/xxx/main.py:35: SyntaxWarning: invalid escape sequence '\d'
  .query('Date.str.contains(r"^\d|^$", na=True) & ~Reference.str.contains(r"^$")', engine='python')
/xxx/main.py:126: SyntaxWarning: invalid escape sequence '\d'
  Description=lambda x: x['Description'].str.replace('_\d{5,}', '', regex=True),
Traceback (most recent call last):
  File "/xxx/main.py", line 2, in <module>
    import pandas as pd
  File "/xxx/images/.venv/lib/python3.12/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/xxx/images/.venv/lib/python3.12/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/xxx/images/.venv/lib/python3.12/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/xxx/images/.venv/lib/python3.12/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/xxx/images/.venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/images/.venv/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

We shall ignore syntax warning first, note the ValueError at the end. This error indicates a binary incompatibility between numpy and pandas. Most likely this issue is due to numpy 2 being installed automatically by pandas

Related SO answer: https://stackoverflow.com/a/78641304

3. camelot-py PDF's issue

```
/xxx/main.py:35: SyntaxWarning: invalid escape sequence '\d'
  .query('Date.str.contains(r"^\d|^$", na=True) & ~Reference.str.contains(r"^$")', engine='python')
/xxx/main.py:126: SyntaxWarning: invalid escape sequence '\d'
  Description=lambda x: x['Description'].str.replace('_\d{5,}', '', regex=True),
Traceback (most recent call last):
  File "/xxx/main.py", line 25, in <module>
    table = camelot.read_pdf(PDF_LINK, pages='all', flavor='stream',
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/images/.venv/lib/python3.12/site-packages/camelot/io.py", line 111, in read_pdf
    p = PDFHandler(filepath, pages=pages, password=password)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/images/.venv/lib/python3.12/site-packages/camelot/handlers.py", line 50, in __init__
    self.pages = self._get_pages(pages)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/images/.venv/lib/python3.12/site-packages/camelot/handlers.py", line 75, in _get_pages
    infile = PdfFileReader(f, strict=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/images/.venv/lib/python3.12/site-packages/PyPDF2/_reader.py", line 1974, in __init__
    deprecation_with_replacement("PdfFileReader", "PdfReader", "3.0.0")
  File "/xxx/images/.venv/lib/python3.12/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/xxx/images/.venv/lib/python3.12/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
```

Note the PyPDF2 deprecation error at the end.

That's all the issues I faced so far.

**Comment by andytan0727** [comment]
Now creating a PR to settle this
